Tests
dan-lee/500-server pull request #1
Opened 2017-04-07 07:57 UTC by robeeeert

:kiss:

2017-04-10 20:21 UTC, dan-lee requested changes

2017-04-10 20:21 UTC, dan-lee commented on package.json
> +  "dependencies": {
We should add this as devDependency :)

2017-04-10 20:21 UTC, dan-lee commented on test/simple.js
> +      server = spawn('node', ['index.js', '5000'])
Great idea :)

2017-04-10 20:21 UTC, dan-lee commented
Great PR :+1:

2017-04-11 07:52 UTC, robeeeert commented on package.json
> +  "dependencies": {
Of course, sorry :)

2017-04-13 08:11 UTC, dan-lee approved these changes

2017-04-13 08:11 UTC, merged